## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./mvnw verify -B

      - name: install ssh key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ORAVM }}
      - name: create .ssh/known_hosts
        run: |
          ssh-keyscan -H -t rsa -v 130.61.159.92  >> ~/.ssh/known_hosts

      - name: copy file to remote server
        run: |
          scp -i ${{ secrets.ORAVM }} /home/runner/work/gh-action-demo/gh-action-demo/target/gh-action-demo-1.0.0-SNAPSHOT.jar 130.61.159.92:/opt
        env:
          my_ssh_key: ${{ secrets.SSH_KEY }}
