## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./mvnw package -B

      - name: install ssh key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ORAVM }}

      - name: create .ssh/known_hosts
        run: |
          ssh-keyscan -H -t rsa -v ${{ secrets.ORAVM_IP }}  >> ~/.ssh/known_hosts

      - name: copy file to remote server
        run: |
          ls -l target/
          scp target/gh-action-demo-1.0.0-SNAPSHOT-runner.jar ${{ secrets.ORAVM_USER }}@${{ secrets.ORAVM_IP }}:
#        with:
#          src: /home/runner/work/gh-action-demo/gh-action-demo/target/gh-action-demo-1.0.0-SNAPSHOT.jar
#          host: 130.61.159.92
#          remote: /opt
#          port: 22
#          user: ubuntu
#          key: ${{ secrets.ORAVM }}

      - name: start on server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: java -jar ~/gh-action-demo-1.0.0-SNAPSHOT-runner.jar
          host: ${{ secrets.ORAVM_IP }}
          username: ${{ secrets.ORAVM_USER }}
          privateKey: ${{ secrets.ORAVM }}

